// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD-16psM9VtY4UQP2kj4KteQepN35ekag',
    appId: '1:390223248897:android:b58fe85add5c47c2a28a00',
    messagingSenderId: '390223248897',
    projectId: 'best-touch-app-df27b',
    storageBucket: 'best-touch-app-df27b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyXl7D3F8ub1amuXIG7ZhWh1635iMi5Fc',
    appId: '1:390223248897:ios:a4a4633e77fd56a2a28a00',
    messagingSenderId: '390223248897',
    projectId: 'best-touch-app-df27b',
    storageBucket: 'best-touch-app-df27b.appspot.com',
    iosBundleId: 'com.example.bestTouchTraining',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_Ag89uaHaAVCanAClOaRT6afhBtuOiJY',
    appId: '1:390223248897:web:54eb378b0d0b5d15a28a00',
    messagingSenderId: '390223248897',
    projectId: 'best-touch-app-df27b',
    authDomain: 'best-touch-app-df27b.firebaseapp.com',
    storageBucket: 'best-touch-app-df27b.appspot.com',
    measurementId: 'G-28K2DX83JP',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyXl7D3F8ub1amuXIG7ZhWh1635iMi5Fc',
    appId: '1:390223248897:ios:a4a4633e77fd56a2a28a00',
    messagingSenderId: '390223248897',
    projectId: 'best-touch-app-df27b',
    storageBucket: 'best-touch-app-df27b.appspot.com',
    iosBundleId: 'com.example.bestTouchTraining',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_Ag89uaHaAVCanAClOaRT6afhBtuOiJY',
    appId: '1:390223248897:web:ee1fc06a5cf8a1a0a28a00',
    messagingSenderId: '390223248897',
    projectId: 'best-touch-app-df27b',
    authDomain: 'best-touch-app-df27b.firebaseapp.com',
    storageBucket: 'best-touch-app-df27b.appspot.com',
    measurementId: 'G-92QV184RMW',
  );
}
